### ISSUE TITLE
Claude Code does not have access to the terminal in github actions

### ISSUE THREAD

**Issue by 0xBigBoss** [0xsend/sendapp#1510]
**Is your feature request related to a problem? Please describe.**

Claude code github action was recently added. Currently, it can only modify the code files and is limited in it's functionality since many permissions are missing.

**Describe the solution you'd like**
I'd like to increase the tools it can use in github actions.

**Additional context**

```
- uses: anthropics/claude-code-action@beta
  with:
    allowed_tools: "Bash(npm install),Bash(npm run test),Edit,Replace,NotebookEditCell"
    disallowed_tools: "TaskOutput,KillTask"
    # ... other inputs
```

https://github.com/anthropics/claude-code-action?tab=readme-ov-file#custom-tools
